- name: add Google DNS to /etc/resolv.conf
  lineinfile:
    path: /etc/resolv.conf
    line: "nameserver 8.8.8.8"

- name: "install EPEL Yum repository"
  yum:
    name: "epel-release"
    state: installed