---
- { include: hosts.yml, when: "groups['master']|length > 0" }
- { include: epel.yml, when: "groups['hosts']|length > 0" }
- { include: rabbitmq.yml, when: "groups['rabbitmq']|length > 0" }
- { include: cluster.yml, when: "groups['slaves']|length > 0" }
- { include: haproxy.yml, when: "groups['haproxy']|length > 0" }