---
- { import_playbook: hosts.yml, when: "groups['master']|length > 0" }
- { import_playbook: epel.yml, when: "groups['hosts']|length > 0" }
- { import_playbook: rabbitmq.yml, when: "groups['rabbitmq']|length > 0" }
- { import_playbook: cluster.yml, when: "groups['slaves']|length > 0" }
- { import_playbook: haproxy.yml, when: "groups['haproxy']|length > 0" }